name: Better_Collect
# 触发条件
on:
  ##push的时候触发
  #push:
  #  branches: master
  workflow_dispatch:
  # 定时触发
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
    - cron: "30 */2 * * *"
jobs:
  Merge_ermaozi:
    runs-on: ubuntu-latest
    steps:
      - name: Post_Code
        uses: actions/checkout@v2
      - name: Setup_Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Load_Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup_TimeZone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Set_Requirements
        run: |
          pip install -r ./requirements/ermaozi/requirements.txt
      - name: Set_SSH_Private_Keys
        env:
          token_Private_Keys: ${{ secrets.token_Private_Keys }}
        run: |
          mkdir -p ~/.ssh/
          echo "$token_Private_Keys" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      - name: Collect_ermaozi
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config pull.rebase false
          git pull
          python ./utils/ermaozi_get_cfmem.py
          git config --global user.name "$username"
          git config --global user.email "$email"
          git config core.ignorecase false
          git add ./sub/clash.yml
          git add ./sub/v2ray.txt
          git commit --allow-empty -m "$(date '+%Y-%m-%d %H:%M:%S') Collect_ermaozi"
          git config pull.rebase false
          git pull
          git push -f origin master
      - name: Delete_More_workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
  Merge_ronghuaxueleng:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set_Requirements
        run: |
          pip install -r ./requirements/ronghuaxueleng/requirements.txt
      - name: Set_SSH_Private_Keys
        env:
          token_Private_Keys: ${{ secrets.token_Private_Keys }}
        run: |
          mkdir -p ~/.ssh/
          echo "$token_Private_Keys" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      - name: Collect_ronghuaxueleng
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config pull.rebase false
          git pull
          python3 ./utils/ronghuaxueleng_get_clash.py
          git config --global user.name "$username"
          git config --global user.email "$email"
          git add ./sub/changfengoss.yaml
          git commit --allow-empty -m "$(date '+%Y.%m.%d %H:%M:%S') Collect_ronghuaxueleng"
          git config pull.rebase false
          git pull
          git push -f origin master
      - name: init_subconverter
        run: |
          wget https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz&&tar -zxvf subconverter_linux64.tar.gz&&nohup ./subconverter/subconverter &
      - name: Collect_cf
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
          git config pull.rebase false
          git pull
          wget "http://127.0.0.1:25500/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2F666greatChina888%2FCode-Store%2Fmaster%2Fsub%2Fchangfengoss.yaml&insert=true&config=https%3A%2F%2Fraw.githubusercontent.com%2FMeilieage%2Fwebcdn%2Fmain%2Frule%2FArea_Media_NoAuto.ini&include=HK%7C%F0%9F%87%AD%F0%9F%87%B0%7CCN%7C%F0%9F%87%A8%F0%9F%87%B3%7CTW%7C%F0%9F%87%B9%F0%9F%87%BC%7C%E6%B8%AF%7C%E4%B8%AD%7C%E5%8F%B0&append_type=true&emoji=true&list=true&udp=true&tfo=false&expand=true&scv=true&fdn=true&sort=true&surge.doh=true&clash.doh=true&new_name=true" -O ./sub/cf_clash_hkcntw.yaml --no-check-certificate
          wget "http://127.0.0.1:25500/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2F666greatChina888%2FCode-Store%2Fmaster%2Fsub%2Fchangfengoss.yaml&insert=true&config=https%3A%2F%2Fraw.githubusercontent.com%2FMeilieage%2Fwebcdn%2Fmain%2Frule%2FArea_Media_NoAuto.ini&include=US%7C%F0%9F%87%BA%F0%9F%87%B8%7CCA%7C%F0%9F%87%A8%F0%9F%87%A6%7CAU%7C%F0%9F%87%A6%F0%9F%87%BA%7C%E7%BE%8E%7C%E5%8A%A0%7C%E6%BE%B3&append_type=true&emoji=true&list=true&udp=true&tfo=false&expand=true&scv=true&fdn=true&sort=true&surge.doh=true&clash.doh=true&new_name=true" -O ./sub/cf_clash_uscaau.yaml --no-check-certificate
          wget "http://127.0.0.1:25500/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2F666greatChina888%2FCode-Store%2Fmaster%2Fsub%2Fchangfengoss.yaml&insert=true&config=https%3A%2F%2Fraw.githubusercontent.com%2FMeilieage%2Fwebcdn%2Fmain%2Frule%2FArea_Media_NoAuto.ini&include=KR%7C%F0%9F%87%B0%F0%9F%87%B7%7CJP%7C%F0%9F%87%AF%F0%9F%87%B5%7CSG%7C%F0%9F%87%B8%F0%9F%87%AC%7C%E9%9F%A9%7C%E6%97%A5%7C%E6%96%B0&append_type=true&emoji=true&list=true&udp=true&tfo=false&expand=true&scv=true&fdn=true&sort=true&surge.doh=true&clash.doh=true&new_name=true" -O ./sub/cf_clash_krjpsg.yaml --no-check-certificate
          wget "http://127.0.0.1:25500/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2F666greatChina888%2FCode-Store%2Fmaster%2Fsub%2Fchangfengoss.yaml&insert=true&config=https%3A%2F%2Fraw.githubusercontent.com%2FMeilieage%2Fwebcdn%2Fmain%2Frule%2FArea_Media_NoAuto.ini&exclude=KR%7C%F0%9F%87%B0%F0%9F%87%B7%7CJP%7C%F0%9F%87%AF%F0%9F%87%B5%7CSG%7C%F0%9F%87%B8%F0%9F%87%AC%7C%E9%9F%A9%7C%E6%97%A5%7C%E6%96%B0%7CUS%7C%F0%9F%87%BA%F0%9F%87%B8%7CCA%7C%F0%9F%87%A8%F0%9F%87%A6%7CAU%7C%F0%9F%87%A6%F0%9F%87%BA%7C%E7%BE%8E%7C%E5%8A%A0%7C%E6%BE%B3%7CHK%7C%F0%9F%87%AD%F0%9F%87%B0%7CCN%7C%F0%9F%87%A8%F0%9F%87%B3%7CTW%7C%F0%9F%87%B9%F0%9F%87%BC%7C%E6%B8%AF%7C%E4%B8%AD%7C%E5%8F%B0&append_type=true&emoji=true&list=true&udp=true&tfo=false&expand=true&scv=true&fdn=true&sort=true&surge.doh=true&clash.doh=true&new_name=true" -O ./sub/cf_clash_others.yaml --no-check-certificate
          git add ./sub/cf_clash_hkcntw.yaml
          git add ./sub/cf_clash_uscaau.yaml
          git add ./sub/cf_clash_krjpsg.yaml
          git add ./sub/cf_clash_others.yaml
          git commit --allow-empty -m "$(date '+%Y.%m.%d %H:%M:%S') Collect_cf"
          git config pull.rebase false
          git pull
          git push -f origin master 
      - name: Delete_More_workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
  Merge_End:
    #needs: [Merge_ronghuaxueleng]
    needs: [Merge_ronghuaxueleng, Merge_ermaozi]
    runs-on: ubuntu-latest
    steps:
      - name: Set_SSH_Private_Keys
        env:
          token_Private_Keys: ${{ secrets.token_Private_Keys }}
        run: |
          mkdir -p ~/.ssh/
          echo "$token_Private_Keys" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      - name: Good_Luck
        env:
          END_STR: Merge All Nodes
        run: |
          echo $END_STR
      - name: Delete_More_workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1